// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// MMD_l_cpp
NumericVector MMD_l_cpp(NumericVector x_obs, NumericVector x_sim, NumericVector sigma, bool permute);
RcppExport SEXP _EasyMMD_MMD_l_cpp(SEXP x_obsSEXP, SEXP x_simSEXP, SEXP sigmaSEXP, SEXP permuteSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x_obs(x_obsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type x_sim(x_simSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< bool >::type permute(permuteSEXP);
    rcpp_result_gen = Rcpp::wrap(MMD_l_cpp(x_obs, x_sim, sigma, permute));
    return rcpp_result_gen;
END_RCPP
}
// shuffle_arma
NumericVector shuffle_arma(NumericVector x);
RcppExport SEXP _EasyMMD_shuffle_arma(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(shuffle_arma(x));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_EasyMMD_MMD_l_cpp", (DL_FUNC) &_EasyMMD_MMD_l_cpp, 4},
    {"_EasyMMD_shuffle_arma", (DL_FUNC) &_EasyMMD_shuffle_arma, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_EasyMMD(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
