# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

kernelMatrix_sum <- function(x_obs, x_sim, sigma) {
    .Call('_EasyMMD_kernelMatrix_sum', PACKAGE = 'EasyMMD', x_obs, x_sim, sigma)
}

kernelMatrix_poly_sum <- function(x_obs, x_sim, sigma) {
    .Call('_EasyMMD_kernelMatrix_poly_sum', PACKAGE = 'EasyMMD', x_obs, x_sim, sigma)
}

