# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

kernelMatrix_sum <- function(x, y, sigma, approx_exp) {
    .Call('_EasyMMD_kernelMatrix_sum', PACKAGE = 'EasyMMD', x, y, sigma, approx_exp)
}

kernelMatrix_threshold_sums <- function(x_u, y_u, sigma, threshold, approx_exp) {
    .Call('_EasyMMD_kernelMatrix_threshold_sums', PACKAGE = 'EasyMMD', x_u, y_u, sigma, threshold, approx_exp)
}

